version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: tooltracker-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbtooltracker
      MYSQL_USER: ghff13
      MYSQL_PASSWORD: "LJL!(D`ooACL<3P>6?^9u:nPl\\lgc'@jGUJo0cDLfM\\c--\\,V.2Nkb;KaK3*X^pm"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

volumes:
  mysql-data:

